<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           attributeFormDefault="unqualified">
    <xs:simpleType name="ProfileIdType">
        <xs:restriction base="xs:string">
            <xs:pattern value="[a-z0-9]+(-[a-z0-9]+)*"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ValueSourceType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="direct_value"/>
            <xs:enumeration value="file_content"/>
            <xs:enumeration value="secret_content"/>
            <xs:enumeration value="environment_variable_content"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="ValueReferenceType">
        <xs:sequence>
            <xs:element name="Source" type="ValueSourceType"/>
            <xs:element name="Value">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:minLength value="1"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BasicType">
        <xs:sequence>
            <xs:element name="Username" type="ValueReferenceType"/>
            <xs:element name="Password" type="ValueReferenceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="BearerType">
        <xs:sequence>
            <xs:element name="Token" type="ValueReferenceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ApiKeyType">
        <xs:sequence>
            <xs:element name="ApiKey" type="ValueReferenceType"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="CertificateType">
        <xs:sequence>
            <xs:element name="Certificate" type="ValueReferenceType"/>
            <xs:element name="PrivateKey" type="ValueReferenceType" minOccurs="0"/>
            <xs:element name="PrivateKeyPassword" type="ValueReferenceType" minOccurs="0"/>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="ProfileType">
        <xs:choice minOccurs="1" maxOccurs="unbounded">
            <xs:element name="Basic" type="BasicType"/>
            <xs:element name="Bearer" type="BearerType"/>
            <xs:element name="ApiKey" type="ApiKeyType"/>
            <xs:element name="Certificate" type="CertificateType"/>
        </xs:choice>
        <xs:attribute name="Id" type="ProfileIdType" use="required"/>
    </xs:complexType>

    <xs:element name="CredentialDocument">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="Profile" type="ProfileType" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
        <xs:unique name="UniqueProfileId">
            <xs:selector xpath="Profile"/>
            <xs:field xpath="@Id"/>
        </xs:unique>
    </xs:element>
</xs:schema>
